#! /bin/sh
LAST_COMMIT_MESSAGE="$(git show -s --format=%s)";
LAST_TAG="chore(release): $(git describe --tags --abbrev=0)";

if [ "$LAST_COMMIT_MESSAGE" != "$LAST_TAG" ]; then
  echo true
else
  echo false
fi
