name: Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: npx nx build firestore --with-deps
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  release:
    name: Release
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Install node packages
        run: npm ci
      - name: Download production artifacts
        uses: actions/download-artifact@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Download production artifacts
        uses: actions/download-artifact@v2
      - name: Set Package Version to Environment
        run: echo PACKAGE_VERSION=$(node -pe '`v${require("./package.json")["version"]}`') >> $GITHUB_ENV
      - name: Publish @nx-ddd/common
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish:common
      - name: Publish @nx-ddd/firestore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish:firestore
        