name: Publish
on:
  workflow_run:
    workflows:
      - Release
    branches:
      - main
    types:
      - completed
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - name: Set Package Version to Environment
        run: echo PACKAGE_VERSION=$(node -pe '`v${require("./package.json")["version"]}`') >> $GITHUB_ENV
      - run: npm ci
      - run: npx nx build firestore --with-deps
      - name: Publish @nx-ddd/common
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish:common
      - name: Publish @nx-ddd/firestore
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish:firestore
        