name: Production
on: push
jobs:
  release:
    runs-on: ubuntu-18.04
    outputs:
      is_released: ${{ steps.result.outputs.is_released }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "is_released $(sh ./.github/scripts/is-released)"
      - id: result
        run: echo "::set-output name=is_released::$(sh ./.github/scripts/is-released)"
  publish:
    runs-on: ubuntu-18.04
    needs: release
    if: ${{needs.release.outputs.is_released == true}}
    steps:
      - run: echo "is_released ${{needs.release.outputs.is_released}}"