name: Production
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    outputs:
      is_version_changed: ${{ steps.step1.result.is_version_changed }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - id: result
        run: echo "::set-output is_version_changed=$(sh ./.github/scripts/is-version-changed)"
  release:
    runs-on: ubuntu-18.04
    needs: build
    if: ${{ needs.build.outputs.is_version_changed == 1 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: echo "is_version_changed ${{needs.build.outputs.is_version_changed}}"