name: Production
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    outputs:
      is_version_changed: ${{ steps.result.outputs.is_version_changed }}
    steps:
      - id: result
        run: echo "::set-output name=is_version_changed::1"
  release:
    runs-on: ubuntu-18.04
    needs: build
    if: ${{needs.build.outputs.is_version_changed == 1}}
    steps:
      - run: echo "is_version_changed ${{needs.build.outputs.is_version_changed}}"