name: Test
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    outputs:
      is_released: ${{ steps.result.outputs.is_released }}
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16.x
      #     cache: npm
      # - name: Install node packages
      #   run: npm i
      # - name: Download production artifacts
      #   uses: actions/download-artifact@v2
      # - env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # run: npx semantic-release
      - id: result
        run: is_released=$(sh ./.github/scripts/is-released); echo "::set-output name=is_released::$is_released"
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs: release
    if: needs.release.outputs.is_released == 'true'
    steps:
      - uses: actions/checkout@v2
        